/*
 * Copyright 2010-2016 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.kotlin.js.test.semantics;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("js/js.translator/testData/jsName/cases")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class JsNameTestGenerated extends AbstractJsNameTest {
    public void testAllFilesPresentInCases() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("js/js.translator/testData/jsName/cases"), Pattern.compile("^(.+)\\.kt$"), true);
    }

    @TestMetadata("avoidNameClash.kt")
    public void testAvoidNameClash() throws Exception {
        String fileName = KotlinTestUtils.navigationMetadata("js/js.translator/testData/jsName/cases/avoidNameClash.kt");
        doTest(fileName);
    }

    @TestMetadata("classes.kt")
    public void testClasses() throws Exception {
        String fileName = KotlinTestUtils.navigationMetadata("js/js.translator/testData/jsName/cases/classes.kt");
        doTest(fileName);
    }

    @TestMetadata("overriddenMethod.kt")
    public void testOverriddenMethod() throws Exception {
        String fileName = KotlinTestUtils.navigationMetadata("js/js.translator/testData/jsName/cases/overriddenMethod.kt");
        doTest(fileName);
    }

    @TestMetadata("overridenFromInterface.kt")
    public void testOverridenFromInterface() throws Exception {
        String fileName = KotlinTestUtils.navigationMetadata("js/js.translator/testData/jsName/cases/overridenFromInterface.kt");
        doTest(fileName);
    }

    @TestMetadata("privateMethod.kt")
    public void testPrivateMethod() throws Exception {
        String fileName = KotlinTestUtils.navigationMetadata("js/js.translator/testData/jsName/cases/privateMethod.kt");
        doTest(fileName);
    }

    @TestMetadata("secondaryConstructor.kt")
    public void testSecondaryConstructor() throws Exception {
        String fileName = KotlinTestUtils.navigationMetadata("js/js.translator/testData/jsName/cases/secondaryConstructor.kt");
        doTest(fileName);
    }

    @TestMetadata("simpleJsName.kt")
    public void testSimpleJsName() throws Exception {
        String fileName = KotlinTestUtils.navigationMetadata("js/js.translator/testData/jsName/cases/simpleJsName.kt");
        doTest(fileName);
    }
}
