/*
 * Copyright 2010-2015 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.kotlin.idea.debugger;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.JetTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("idea/testData/debugger/tinyApp/src/positionManager")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class JetPositionManagerWithDebugProcessTestGenerated extends AbstractJetPositionManagerWithDebugProcessTest {
    public void testAllFilesPresentInPositionManager() throws Exception {
        JetTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/tinyApp/src/positionManager"), Pattern.compile("^(.+)\\.kt$"), true);
    }

    @TestMetadata("pmAnonymousFunction.kt")
    public void testPmAnonymousFunction() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("idea/testData/debugger/tinyApp/src/positionManager/pmAnonymousFunction.kt");
        doTest(fileName);
    }

    @TestMetadata("pmAnonymousNamedFunction.kt")
    public void testPmAnonymousNamedFunction() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("idea/testData/debugger/tinyApp/src/positionManager/pmAnonymousNamedFunction.kt");
        doTest(fileName);
    }

    @TestMetadata("pmClassObject.kt")
    public void testPmClassObject() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("idea/testData/debugger/tinyApp/src/positionManager/pmClassObject.kt");
        doTest(fileName);
    }

    @TestMetadata("pmFunctionLiteral.kt")
    public void testPmFunctionLiteral() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("idea/testData/debugger/tinyApp/src/positionManager/pmFunctionLiteral.kt");
        doTest(fileName);
    }

    @TestMetadata("pmFunctionLiteralInVal.kt")
    public void testPmFunctionLiteralInVal() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("idea/testData/debugger/tinyApp/src/positionManager/pmFunctionLiteralInVal.kt");
        doTest(fileName);
    }

    @TestMetadata("pmLocalFunction.kt")
    public void testPmLocalFunction() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("idea/testData/debugger/tinyApp/src/positionManager/pmLocalFunction.kt");
        doTest(fileName);
    }

    @TestMetadata("pmObjectExpression.kt")
    public void testPmObjectExpression() throws Exception {
        String fileName = JetTestUtils.navigationMetadata("idea/testData/debugger/tinyApp/src/positionManager/pmObjectExpression.kt");
        doTest(fileName);
    }
}
